kind: pipeline
name: build

trigger:
  event:
    - push


volumes:
  - name: docker-socket
    host:
      path: /var/run/docker.sock

steps:
  - name: greeting
    image: alpine
    commands:
      - echo hello
      - echo world

  - name: test
    image: rustdocker/rustup
    environment:
      PATH: /root/.cargo/bin:/usr/bin:/bin:/usr/sbin:/sbin
    commands:
      - rustup toolchain install $(cat rust-toolchain)
      - cargo test --features sqlite
    depends_on:
      - greeting


  - name: build-docker-image
    image: docker
    volumes:
      - name: docker-socket
        path: /var/run/docker.sock
    commands:
      - docker build -f docker/amd64/Dockerfile
    depends_on:
      - greeting


  - name: build-docker-image-alpine
    image: docker
    volumes:
      - name: docker-socket
        path: /var/run/docker.sock
    commands:
      - docker build -f docker/amd64/Dockerfile.alpine
    depends_on:
      - greeting
