kind: pipeline
name: build

trigger:
  event:
    - push

steps:
  - name: greeting
    image: alpine
    commands:
      - echo hello
      - echo world

  - name: build
    image: rustdocker/rustup
    commands:
      - rustup toolchain install $(cat rust-toolchain)
      - cargo check --features sqlite
