kind: pipeline
name: build

trigger:
  event:
    - push


volumes:
  - name: docker-socket
    host:
      path: /var/run/docker.sock

  - name: upstream
    temp: {}


steps:

  - name: build-docker-image
    image: docker
    volumes:
      - name: docker-socket
        path: /var/run/docker.sock
    commands:
      - docker build -f docker/amd64/Dockerfile .
    depends_on:
      - clone

  - name: build-docker-image-alpine
    image: docker
    volumes:
      - name: docker-socket
        path: /var/run/docker.sock
    commands:
      - docker build -f docker/amd64/Dockerfile.alpine .
    depends_on:
      - clone


---
kind: pipeline
name: merge-upstream


trigger:
  event:
    - cron
    - promote
  cron:
    - hourly
  target:
    - production


volumes:
  - name: upstream
    temp: {}

steps:

  - name: merge-upstream
    image: alpine
    commands:
      - git remote add upstream https://github.com/dani-garcia/vaultwarden.git
      - git fetch upstream
      - git checkout master
      - git merge --ff upstream/master
      - git push
